name: dl_grouding
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - tqdm
  - pillow
  - opencv
  - pycocotools
  - cudatoolkit=11.6
  - pytorch=1.13.1       # installa qui torch con CUDA 11.6
  - torchvision=0.14.1
  - pip
  - pip:
    - ultralytics==8.0.20
    - git+https://github.com/openai/CLIP.git
